project:
  type: website
  output-dir: docs

website:
  title: "Carlos Vigil-Vásquez"
  favicon: favicon.ico
  site-url: "https://yoursite.com"
  description: "Personal website of Carlos Vigil-Vásquez, computational biologist, open-source developer, and photographer"
  
format:
  html:
    theme: none
    css: styles.css
    toc: false
    page-layout: full
    margin-header: |
      <div class="header-container">
        <div class="header-spacer"></div>
      </div>
    margin-footer: |
      <div class="footer-spacer"></div>
