* Hi! I'm Carlos &...

I'm a chilean biochemist turned *computational biologist*, I am currently pursuing my PhD at the Université de Lille, focusing on /reconstructing the evolutionary tree of life through the lens of cellular metabolism leveraging novel computational paradigms for biological system representation./

I specialize in *designing and implementing computational experiments to test biological hypotheses*, with experience in bio/chem-informatics, machine learning/AI, and data visualization. Additionally, I have extensive experience on *developing scientific software packages* and it's application solving problems.

My current *research interest* center around:

- Development of novel computational representations of biological systems
- Network biology and it's relationship to biological complexity
- Scientific software development experience

I highly advocate for *open science and open source software* as means for progress based in
collaboration and education.

** Experience

- *PhD Researcher* @ Universite de Lille /(Dec. '24 - today)/
- *Protein Designer* @ Protera Biosciences /(Sept. '23 - Nov '24)/
- *Research Assistant* @ Neurobiology of Aging Lab, USS /(May - Aug. '23)/
- *Research Assistant* @ Molecular Design Lab, PUC /(July '16 - May '23)/
- *Research Assistant* @ Psychophysiology Lab, PUC /(Jan. '22 - Jan. '23)/

** Education

- *PhD* @ Universite de Lille /(Dec. '24 - today)/
- *Bsc. Biochemistry* @ PUC, Chile /(2015 - 2022)/
